import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body>
        <nav className="bg-green-800 text-white p-4 flex gap-4">
          <a href="/" className="hover:underline">
            Home
          </a>
          <a href="/daftar" className="hover:underline">
            Data Pasien
          </a>
          {/* <a href="/reminder" className="hover:underline">
            Reminder
          </a> */}
        </nav>
        {children}
      </body>
    </html>
  );
}
